In [1]:
import numpy as np

array = np.random.random(5) * 10

print("Original array:")
print(array)

# Method 1
method1 = array.astype(int)

# Method 2
method2 = np.floor(array).astype(int)

# Method 3
method3 = np.trunc(array).astype(int)

# Method 4
method4 = np.modf(array)[1].astype(int)

# Method 5
method5 = (array // 1).astype(int)

print("\nMethod 1 - astype:")
print(method1)

print("\nMethod 2 - floor:")
print(method2)

print("\nMethod 3 - trunc:")
print(method3)

print("\nMethod 4 - modf:")
print(method4)

print("\nMethod 5 - floor division:")
print(method5)

Original array:
[5.02153052 6.89243278 1.04181437 6.14902003 7.86738265]

Method 1 - astype:
[5 6 1 6 7]

Method 2 - floor:
[5 6 1 6 7]

Method 3 - trunc:
[5 6 1 6 7]

Method 4 - modf:
[5 6 1 6 7]

Method 5 - floor division:
[5 6 1 6 7]
