In [1]:
import numpy as np

matrix = np.random.random((5, 5))

print("5x5 random array:")
print(matrix)

print("Minimum value:", matrix.min())
print("Maximum value:", matrix.max())

5x5 random array:
[[0.49509419 0.44368846 0.57639673 0.07450942 0.92056891]
 [0.20841439 0.29547872 0.24755579 0.48294058 0.96081979]
 [0.96771673 0.5596062  0.4589459  0.3163342  0.98214482]
 [0.96342826 0.35091644 0.39532007 0.22602067 0.01976434]
 [0.86387412 0.32965533 0.03221449 0.06405196 0.25133068]]
Minimum value: 0.019764341473397673
Maximum value: 0.9821448166063189
