In [1]:
import numpy as np

array = np.array([
    [5, 2, 8],
    [1, 9, 3],
    [7, 4, 6],
    [2, 1, 5]
])

print("Original array:")
print(array)

n = 1

sorted_array = array[array[:, n].argsort()]

print("\nSorted by column", n)
print(sorted_array)

Original array:
[[5 2 8]
 [1 9 3]
 [7 4 6]
 [2 1 5]]

Sorted by column 1
[[2 1 5]
 [5 2 8]
 [7 4 6]
 [1 9 3]]
