In [1]:
import numpy as np

A = np.random.random((5, 3))
B = np.random.random((3, 2))

result = A @ B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix product:")
print(result)

Matrix A:
[[0.46524378 0.79773081 0.55932866]
 [0.10378356 0.05051912 0.43443256]
 [0.90445068 0.41242243 0.93910936]
 [0.75189558 0.29958235 0.66303585]
 [0.90447369 0.81485959 0.31806468]]

Matrix B:
[[0.68495414 0.68301036]
 [0.58520582 0.17454397]
 [0.43884565 0.07811474]]

Matrix product:
[[1.03096631 0.50069724]
 [0.2912999  0.11363864]
 [1.27298331 0.76309332]
 [0.98130173 0.61763564]
 [1.23596488 0.78483927]]
