In [1]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 1, 1]
])

print("Matrix:")
print(matrix)

rank = np.linalg.matrix_rank(matrix)

print("\nMatrix rank:")
print(rank)

Matrix:
[[1 2 3]
 [2 4 6]
 [1 1 1]]

Matrix rank:
2
