In [1]:
import numpy as np

matrix = np.random.random((4, 5))

print("Original matrix:")
print(matrix)

row_means = matrix.mean(axis=1, keepdims=True)

result = matrix - row_means

print("\nMean of each row:")
print(row_means)

print("\nMatrix after subtracting row means:")
print(result)

Original matrix:
[[0.69738892 0.98657927 0.7938319  0.14180399 0.22516726]
 [0.66579297 0.49319553 0.14527319 0.12109493 0.34078186]
 [0.00876384 0.81240648 0.70571128 0.38935362 0.77477113]
 [0.00426114 0.77556968 0.68779766 0.58690309 0.18613077]]

Mean of each row:
[[0.56895427]
 [0.35322769]
 [0.53820127]
 [0.44813247]]

Matrix after subtracting row means:
[[ 0.12843465  0.41762501  0.22487763 -0.42715028 -0.34378701]
 [ 0.31256527  0.13996783 -0.2079545  -0.23213277 -0.01244584]
 [-0.52943743  0.27420521  0.16751001 -0.14884765  0.23656986]
 [-0.44387132  0.32743721  0.23966519  0.13877062 -0.2620017 ]]
