In [1]:
import numpy as np

matrix = np.random.random((5, 5))

print("Original matrix:")
print(matrix)

normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())

print("\nNormalized matrix:")
print(normalized_matrix)

Original matrix:
[[0.27652701 0.77473141 0.56567188 0.3923444  0.19930312]
 [0.50741155 0.30839413 0.83964156 0.65778915 0.59257293]
 [0.63372441 0.93274779 0.79365243 0.59509769 0.3276427 ]
 [0.98567367 0.23711329 0.26559961 0.12235324 0.3801461 ]
 [0.51438768 0.31715878 0.74226848 0.64570376 0.88397712]]

Normalized matrix:
[[0.17858233 0.75566169 0.51350417 0.31273575 0.08913247]
 [0.44602016 0.21549461 0.83084832 0.62020531 0.54466416]
 [0.59233068 0.93869498 0.77757825 0.54758863 0.23779058]
 [1.         0.13292868 0.16592492 0.         0.29860623]
 [0.45410074 0.22564686 0.71805928 0.60620658 0.88220301]]
